<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_chamaedorea_elegans</name>
   <tag></tag>
   <elementGuidId>8dfad139-21d5-40e8-9126-090e835b8c76</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'product-details')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>:root > :nth-child(2) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/main[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-details</value>
      <webElementGuid>de986188-0626-47e1-a793-6974f013c90a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
