<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fda6e91a-7e5d-453a-a06c-a7a7f61ce8bd</elementGuidId>
    <imagePath></imagePath>
    <name>h5_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/div[1]/h5[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="text-overflow-ellipsis"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>