<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6e96eb81-452c-494f-b038-9dff01f3473e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sign_in</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="button\ button-small\ button-muted\ margin-left-s"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>035531ff-0ab1-48c9-ad12-eb88cc6b259b</webElementGuid>
    </webElementProperties>
</WebElementEntity>