<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3a1710d9-ec0d-42dd-9f9d-3c455885c81e</elementGuidId>
    <imagePath></imagePath>
    <name>image_productModalImageCollection5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[1]/div[5]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-modal-image-collection-wrapper"]:nth-child(5) &gt; [class="product-modal-image-collection-img is-img-loaded"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(5) &gt; .product-modal-image-collection-img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>