<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8c3e126e-7336-4396-8019-48cf9e45b604</elementGuidId>
    <imagePath></imagePath>
    <name>image_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-modal-image-collection-wrapper"]:nth-child(2) &gt; [class="product-modal-image-collection-img is-img-loaded"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .product-modal-image-collection-img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>