<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2a67971-18d2-4101-966d-817cb031c009</elementGuidId>
    <imagePath></imagePath>
    <name>link_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/') and equals(@text,'Home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Home"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/</value>
        <webElementGuid>1bf4774d-075c-4a86-a969-d5546c37f435</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Home</value>
        <webElementGuid>1bf4774d-075c-4a86-a969-d5546c37f435</webElementGuid>
    </webElementProperties>
</WebElementEntity>