<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e92cdbb-a438-4ec8-8c0b-671b93145c61</elementGuidId>
    <imagePath></imagePath>
    <name>header_productName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[2]/h5[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-card-name text-overflow-ellipsis margin-auto"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Philodendron Imperial Red"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>