<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>800bf472-434c-4202-8d19-025eb70ca9c0</elementGuidId>
    <imagePath></imagePath>
    <name>div_plantAtreeMakeTheWorld</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="home"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text="Plant a tree, make the world"i &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>