<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a92cdaa1-84fd-44ed-900f-a77466f9632b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="display"]:nth-child(3) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See All')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See All</value>
        <webElementGuid>12a19f96-0e14-4c3f-ac18-95365f277625</webElementGuid>
    </webElementProperties>
</WebElementEntity>