<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d74d473-3df2-4234-9cd3-186b3085ef48</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="display"]:nth-child(3) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See All')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See All</value>
        <webElementGuid>035531ff-0ab1-48c9-ad12-eb88cc6b259b</webElementGuid>
    </webElementProperties>
</WebElementEntity>