<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db999b88-80a8-45cb-9e14-912e4f259304</elementGuidId>
    <imagePath></imagePath>
    <name>link_SignIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.button-muted</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Sign In"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>8396c12a-5d03-4fff-955c-014880a4736b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>8396c12a-5d03-4fff-955c-014880a4736b</webElementGuid>
    </webElementProperties>
</WebElementEntity>