<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>34cfe976-ac67-451b-b033-9bf28e315c2b</elementGuidId>
    <imagePath></imagePath>
    <name>link_viewAccount</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="user-nav-sub-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/account') and equals(@text,'View Account')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="View Account user"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/account</value>
        <webElementGuid>1bf4774d-075c-4a86-a969-d5546c37f435</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View Account</value>
        <webElementGuid>1bf4774d-075c-4a86-a969-d5546c37f435</webElementGuid>
    </webElementProperties>
</WebElementEntity>