<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_order</name>
   <tag></tag>
   <elementGuidId>1080befb-1947-4346-bb28-0fd7c56dc469</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'button button-small ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.product-modal-action .button</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[4]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-small </value>
      <webElementGuid>f68ab08e-2439-4abe-abfa-f05c111bd5ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
