<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba102c00-d833-4e84-8d9a-31a0926faeff</elementGuidId>
    <imagePath></imagePath>
    <name>button_next_step</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[3]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Next Step')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next Step</value>
        <webElementGuid>0634137a-9448-42aa-ad27-b8acac0a5a3f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>0634137a-9448-42aa-ad27-b8acac0a5a3f</webElementGuid>
    </webElementProperties>
</WebElementEntity>