<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d2c10c0-0314-4dcb-ba73-8b708166a06d</elementGuidId>
    <imagePath></imagePath>
    <name>input_creditCardPayWithVisa</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="modeCredit"] &gt; [class="d-flex-grow-1 margin-left-s"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Credit CardPay with Visa,"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>