<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>005d52b1-cacd-4beb-a8d6-47d6aa2ccc50</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[1]/div[4]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-vbgp86-SkeletonTheme"]:nth-child(4) [class="product-details"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>