<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4ed591cf-2831-4244-8c19-f029dedd189c</elementGuidId>
    <imagePath></imagePath>
    <name>div_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="css-vbgp86-SkeletonTheme"]:nth-child(2) [class="product-details"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Herringbone Pine TreeIndoor-Plants$"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>